spring:
  datasource:
    url: jdbc:mysql://localhost:3306/repository01
    username: root
    password: psw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
    show_sql: true4
    hibernate:
      ddl-auto: create-drop
server:
  port: 5050
